test 1

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -25,4 +25,22 @@ jobs:
 
       - name: Run Scan
         run: |
-          docker run -e OSS_USERNAME=pioter530@wp.pl -e OSS_KEY=c3aff65db27c78cb3d4d14e9576afec936d4f74 -e MIXEWAY_URL=https://hub.mixeway.io -e MIXEWAY_KEY=b9181a72-8036-484d-977e-dbfe1187c1fd -e MIXEWAY_PROJECT_ID=191 -e MODE=STANDALONE -e MIXEWAY_PROJECT_NAME=BigCatStudio_lab_secure_app -e COMMIT_ID=test -e BRANCH=master -v ${{ github.workspace }}:/opt/sources mixeway/scanner:latest || exit 1
+          docker run \
+            -e OSS_USERNAME=pioter530@wp.pl \
+            -e OSS_KEY=c3aff65db27c78cb3d4d14e9576afec936d4f74 \
+            -e MIXEWAY_URL=https://hub.mixeway.io \
+            -e MIXEWAY_KEY=b9181a72-8036-484d-977e-dbfe1187c1fd \
+            -e MIXEWAY_PROJECT_ID=191 \
+            -e MODE=STANDALONE \
+            -e MIXEWAY_PROJECT_NAME=BigCatStudio_lab_secure_app \
+            -e COMMIT_ID=test \
+            -e BRANCH=master \
+            -v ${{ github.workspace }}:/opt/sources \
+            mixeway/scanner:latest > result.log
+
+          if grep -q '"severity"' result.log; then
+            echo "Vulnerabilities found! Failing the job."
+            exit 1
+          else
+            echo "No vulnerabilities found."
+          fi
